services:

  flatnotes:
    container_name: flatnotes
    image: dullage/flatnotes:latest
    restart: unless-stopped
    ports:
      - "8100:8080"
    volumes:
      - ./flatnotes/notes:/data
      - ./flatnotes/index:/data/.flatnotes
    environment:
      PUID: "1000"
      PGID: "1000"
      FLATNOTES_AUTH_TYPE: none

  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./linkding-db:/etc/linkding/data

  dashy:
    ## Taken from 
    ## https://github.com/lissy93/dashy/blob/master/docker-compose.yml
    container_name: Dashy
    image: lissy93/dashy:latest
    restart: unless-stopped
    ports:
      - 4000:8080
    volumes:
      - ./dashy-data:/app/user-data
    healthcheck:
      test: [ 'CMD', 'node', '/app/services/healthcheck.js' ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s

  ## Need to find a lighter app, glances takes some CPU
  ## Whenever you need to start it, you can use the shell alias command 'glanes'
  ## and stop it by 'glances-stop'. Both of these start the docker container.

  # glances:
  #   container_name: glances
  #   image: nicolargo/glances:latest
  #   restart: unless-stopped
  #   ports:
  #     - "61208:61208"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   environment:
  #     GLANCES_OPT: -w
  #     PUID: "1000"
  #     PGID: "1000"
  #     TZ: Asia/Kolkata
  #   pid: host
  #   privileged: true

  server:
    container_name: server_self_hosted
    image: standardnotes/server
    restart: unless-stopped
    ports:
      - 3000:3000
      - 3125:3104
    volumes:
      - ./standardnotes/logs:/var/lib/server/logs
      - ./standardnotes/uploads:/opt/server/packages/files/dist/uploads
    env_file: ./standardnotes/.env
    networks:
      - standardnotes_self_hosted

  localstack:
    container_name: localstack_self_hosted
    image: localstack/localstack:3.0
    restart: unless-stopped
    expose:
      - 4566
    volumes:
      - ./standardnotes/localstack_bootstrap.sh:/etc/localstack/init/ready.d/localstack_bootstrap.sh
    environment:
      - SERVICES=sns,sqs
      - HOSTNAME_EXTERNAL=localstack
      - LS_LOG=warn
    networks:
      - standardnotes_self_hosted

  db:
    container_name: db_self_hosted
    image: mysql:8
    restart: unless-stopped
    expose:
      - 3306
    volumes:
      - ./standardnotes/data/mysql:/var/lib/mysql
      - ./standardnotes/data/import:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=standard_notes_db
      - MYSQL_USER=std_notes_user
      - MYSQL_ROOT_PASSWORD=b440ea7a97bb823a23b07fd2
      - MYSQL_PASSWORD=b440ea7a97bb823a23b07fd2
    networks:
      - standardnotes_self_hosted

  cache:
    container_name: cache_self_hosted
    image: redis:6.0-alpine
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - ./standardnotes/data/redis/:/data
    networks:
      - standardnotes_self_hosted

networks:
  standardnotes_self_hosted:
    name: standardnotes_self_hosted
